MONGODB_HOST: mongodb-{{ env }}.daws-86s.space
REDIS_HOST: redis-{{ env }}.daws-86s.space
CATALOGUE_HOST: catalogue-{{ env }}.daws-86s.space
CART_HOST: cart-{{ env }}.daws-86s.space
USER_HOST: user-{{ env }}.daws-86s.space
RABBITMQ_HOST: rabbitmq-{{ env }}.daws-86s.space
MYSQL_HOST: mysql-{{ env }}.daws-86s.space
SHIPPING_HOST: shipping-{{ env }}.daws-86s.space
PAYMENT_HOST: payment-{{ env }}.daws-86s.space