[mongodb]
localhost

[catalogue]
catalogue.daws-86s.space

[cart]
cart.daws-86s.space

[mysql]
localhost

[redis]
localhost

[rabbitmq]
localhost

[user]
user.daws-86s.space

[shipping]
shipping.daws-86s.space

[payment]
payment.daws-86s.space

[frontend]
frontend.daws-86s.space

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
